name: CI - DevOps Monitoring Platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python  # Исправлено: было "Pythron"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies  # Исправлено: было "dependecies"
        run: |
          python -m pip install --upgrade pip
          pip install fastapi prometheus-client psutil httpx pytest flake8
          # ИЛИ если у вас есть requirements.txt:
          # pip install -r requirements.txt
          # pip install pytest flake8

      - name: Lint code (flake8)
        run: |
          flake8 app --max-line-length=100

      - name: Run tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t devops-monitoring-app .
